module Hello

from "./expression.gr" include Tree
from "./lexing.gr" include Lexing
from "./evaluator.gr" include Evaluator

from "list" include List
from "buffer" include Buffer
from "result" include Result
from "bytes" include Bytes
from "wasi/file" include File

//print("Expression: ")
//let input = File.fdRead(File.stdin, 40000)
//let input = Result.unwrap(input)

let value = Evaluator.eval("1+2*3-4")

print(value)
